runtime: python312
service: default

env_variables:
  GOOGLE_CLOUD_PROJECT: "cedar-router-466020-s9"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
  - url: /static
    static_dir: frontend
    secure: always

  - url: /.*
    script: auto
    secure: always 